### ISSUE TITLE
Adding flavors: best practice

### ISSUE THREAD

**Issue by afgane** [ARTbio/GalaxyKickStart#180]
We're using this playbook for building VM images on the Jetstream cloud and, in the near future, on the Google Compute Engine. We'd also like to merge these flavors into this upstream repo in case others want to do the same. However, Jetstream in particular, needs some customizations so we put those into its own role. Now, the question is how best to include that role in the upstream codebase without making it verbose? I'd guess one role would even be OK but as we move to GCE and beyond, it's not going to look pretty. Any suggestions of thoughts on this?

Here's an example of what I'm talking about https://github.com/nturaga/ansible-artimed/blob/master/galaxy.yml#L14

**Comment by mvdbeek** [comment]
Hi Enis,

that is awesome, I'm really happy that you are able to adapt the playbook with a single role! 
I have to think about how to best include "flavor roles", but I see some parts of the role that can move to upstream roles (or maybe are already ...)

  - Create shed tools dir and galaxy log dir should normally be done in the ansible-galaxy role (https://github.com/galaxyproject/ansible-galaxy/pull/14) )
  - Create database dir should be done in the postgresql role
  - install samtools in ansible-galaxy-os

The whole cleanup part can be included as a named include handler, so that you need to include the role only once.

I can see a few potential ways to include community/flavor roles, I guess the difficulty is that you may need to have control over the position in the play in which the role will be executed, right?

So the way you have done this right now is completely OK for me if we're expecting just a few additional roles, and it's probably not worth the additional complexity to have a roles variable.

Not sure if this is possible, but maybe can have a structure like this:
```
- hosts: all
  become: yes

  handlers:
    - include: roles/handlers/galaxy.yml
      static: yes

  roles: {{ roles_list}}
```

where

```
roles_list:
    - role: galaxyprojectdotorg.galaxy-os
      tags:
        - install_galaxy
        - install_packages

    - role: jetstream
      when: jetstream is defined

    - role: ensure_postgresql_up
      tags:
        - install_galaxy
        - manage_postgres
```

so that flavors can define their own roles list in the inventory.
